
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-test:
    machine: 
      docker_layer_caching: true
      image: circleci/classic:201808-01

    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: switch python 3.7
          command: |
            pyenv versions
            pyenv global 3.7.0
            cd src && python3.7 -m pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pwd
            scp mvp@demo-app.rebloc.io:/var/local/democonfig/server/.database.ini . 
            scp mvp@demo-app.rebloc.io:/var/local/democonfig/server/root.crt . 
            python3.7 test_app.py

  deploy:
    machine: 
      docker_layer_caching: true
      image: circleci/classic:201808-01
    production:
    branch: master
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            cd src && scp mvp@demo-app.rebloc.io:/var/local/democonfig/server/.database.ini . 
            cd src && scp mvp@demo-app.rebloc.io:/var/local/democonfig/server/root.crt . 
            cd src && pyinstaller -F app.py && docker build -t bernardlin/flaskapi:beta -f Dockerfile.flask .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push bernardlin/flaskapi:beta
      - run:
          name: start up docker
          command: |
            # rsh  mvp@demo-app.rebloc.io "if [ ! -d 'webapp' ]; then mkdir -p webapp; fi"
            # scp -r ./* mvp@demo-app.rebloc.io:/home/mvp/webapp/server/flask
            rsh mvp@demo-app.rebloc.io "cd src && docker pull bernardlin:flaskapi:beta & bash run_api_docker.sh bernardlin:flaskapi:beta"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test