
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-test:
    machine: true
      docker_layer_caching: true

    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            curl -s https://packagecloud.io/install/repositories/circleci/trusty/script.deb.sh | sudo bash
            circleci-install python 3.7.2
            virtualenv flaskapi
            . flaskapi/bin/activate
            cd src && pip3 install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . flaskapi/bin/activate
            cd src && scp mvp@demo-app.rebloc.io:/home/mvp/webapp/server/.database.ini . && python test_app.py
  
  deploy:
    machine: true
    production:
    branch: master
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . flaskapi/bin/activate
            cd src && scp mvp@demo-app.rebloc.io:/home/mvp/webapp/server/.database.ini . && pyinstaller -F app.py && docker build -t bernardlin/flaskapi:beta .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push bernardlin/flaskapi:beta
      - run:
          name: start up docker
          command: |
            # rsh  mvp@demo-app.rebloc.io "if [ ! -d 'webapp' ]; then mkdir -p webapp; fi"
            # scp -r ./* mvp@demo-app.rebloc.io:/home/mvp/webapp/server/flask
            rsh mvp@demo-app.rebloc.io "cd src && docker pull bernardlin:flaskapi:beta & bash run_api_docker.sh bernardlin:flaskapi:beta"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test