
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-test:
    machine: 
      docker_layer_caching: true
      image: circleci/classic:latest

    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install ubuntu build reqs
          command: |
            sudo apt-get update && sudo apt upgrade -y
            sudo apt-get install build-essential libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev libffi-dev
      - run:
          name: install python 3.7
          command: |
            sudo add-apt-repository --yes ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install python3.7
            curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.7 
            sudo python3.7 -m pip install
            sudo python3.7 -m pip install pipenv
            cd src && python3.7 -m pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . flaskapi/bin/activate
            cd src && scp mvp@demo-app.rebloc.io:/home/mvp/webapp/server/.database.ini . && python3.7 test_app.py

  deploy:
    machine: true
    production:
    branch: master
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . flaskapi/bin/activate
            cd src && scp mvp@demo-app.rebloc.io:/home/mvp/webapp/server/.database.ini . && pyinstaller -F app.py && docker build -t bernardlin/flaskapi:beta .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push bernardlin/flaskapi:beta
      - run:
          name: start up docker
          command: |
            # rsh  mvp@demo-app.rebloc.io "if [ ! -d 'webapp' ]; then mkdir -p webapp; fi"
            # scp -r ./* mvp@demo-app.rebloc.io:/home/mvp/webapp/server/flask
            rsh mvp@demo-app.rebloc.io "cd src && docker pull bernardlin:flaskapi:beta & bash run_api_docker.sh bernardlin:flaskapi:beta"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test